# Generated by Django 3.1.7 on 2021-05-09 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kontrah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_kontrahent', models.IntegerField()),
                ('kontrahe', models.CharField(max_length=100, verbose_name='Kontrahent')),
                ('DL_kontrahent', models.CharField(max_length=500, verbose_name='Kontrahent Nazwa Długa')),
            ],
            options={
                'verbose_name': 'Kontrahent',
                'verbose_name_plural': 'Kontrahenci',
            },
        ),
        migrations.CreateModel(
            name='Pracownik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Praownikdane', models.CharField(max_length=500, verbose_name='Dane Pracownika')),
            ],
            options={
                'verbose_name': 'Pracownik',
                'verbose_name_plural': 'Pracownik',
            },
        ),
        migrations.CreateModel(
            name='XXX_Kontrah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_kontrahent', models.IntegerField()),
                ('kontrahe', models.CharField(max_length=100, verbose_name='Kontrahent')),
                ('DL_kontrahent', models.CharField(max_length=500, verbose_name='Kontrahent Nazwa Długa')),
            ],
            options={
                'verbose_name': 'XXX_Kontrahent',
                'verbose_name_plural': 'XXX_Kontrahenci',
            },
        ),
        migrations.CreateModel(
            name='ZUS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zus10', models.CharField(max_length=100)),
                ('zus15', models.CharField(max_length=100)),
                ('PIT_4', models.CharField(max_length=100)),
                ('LP', models.CharField(max_length=100)),
                ('RACH', models.CharField(max_length=100)),
                ('czas_realizacj', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('kontrahent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mask.kontrah')),
                ('pracownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mask.pracownik')),
            ],
            options={
                'verbose_name': 'ZUS',
                'verbose_name_plural': 'ZUS',
            },
        ),
        migrations.CreateModel(
            name='US',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilosc_dokumentow', models.IntegerField()),
                ('okres_Pit_Cit', models.CharField(max_length=100)),
                ('okres_Vat', models.CharField(max_length=100)),
                ('weryfikacja_rej_Vat', models.CharField(max_length=100)),
                ('Vat_JPK', models.CharField(max_length=100)),
                ('czas_realizacj', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('kontrahent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mask.kontrah')),
                ('pracownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mask.pracownik')),
            ],
            options={
                'verbose_name': 'US',
                'verbose_name_plural': 'US',
            },
        ),
    ]
