# Generated by Django 3.1.7 on 2021-05-22 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mask.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mask', '0002_auto_20210518_2158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slownik1',
            old_name='wartosc',
            new_name='wartosc1',
        ),
        migrations.RenameField(
            model_name='slownik2',
            old_name='wartosc',
            new_name='wartosc2',
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to=mask.models.content_file_name)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
